version: "3.9"

services:
    api:
        build:
            context: ./server
            dockerfile: Dockerfile
        image: fetchly-api:latest
        container_name: fetchly-api
        environment:
            - TZ=UTC
        ports:
            - "8000:8000"
        restart: unless-stopped

    web:
        build:
            context: ./client
            dockerfile: Dockerfile
        image: fetchly-web:latest
        container_name: fetchly-web
        environment:
            - TZ=UTC
            - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
        ports:
            - "3000:3000"
        depends_on:
            - api
        restart: unless-stopped

    nginx:
        image: nginx:alpine
        container_name: fetchly-proxy
        depends_on:
            - api
            - web
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        restart: unless-stopped
